<SettingsScreen>:
    FloatLayout:

        MDLabel:
            pos_hint:{"x":.3, "y": .9}
            size_hint:(.2,.1)
            text: "Modo Noche: "
            halign: "center"
            theme_text_color:"Primary"
        
        MDSwitch:
            id: mode
            pos_hint:{"x":.5, "y": .9}
            size_hint:(.05,.1)
            on_active: root.change_mode(*args)


        